"""licenses table: +expiration_date-DEFAULT_value

Revision ID: 156d262b5c7f
Revises: e21f42d43f76
Create Date: 2025-05-24 19:21:55.145661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156d262b5c7f'
down_revision: Union[str, None] = 'e21f42d43f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses',
                  sa.Column('expiration_date',
                            sa.DateTime(),
                            server_default=sa.text('now() + make_interval(secs=>2592000.0)'),
                            nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'expiration_date')
    # ### end Alembic commands ###
