"""licenses table: +expiration_date-nullable=FALSE

Revision ID: e21f42d43f76
Revises: 31ba8d2379b7
Create Date: 2025-05-24 18:56:17.127773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21f42d43f76'
down_revision: Union[str, None] = '31ba8d2379b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('expiration_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'expiration_date')
    # ### end Alembic commands ###
